// Auth
export const AUTH_USER_LOGGED_IN = 'AUTH_USER_LOGGED_IN';
export const AUTH_USER_LOGGED_OUT = 'AUTH_USER_LOGGED_OUT';

// Movies
export const GET_ALL_MOVIES = 'GET_ALL_MOVIES';
export const GET_MOVIE_DETAIL = 'GET_MOVIE_DETAIL';
export const DELETE_SELECTED_MOVIE_DETAIL = 'DELETE_SELECTED_MOVIE_DETAIL';
export const ADD_MOVIE_TO_WATCHLIST = 'ADD_MOVIE_TO_WATCHLIST';
export const REMOVE_MOVIE_FROM_WATCHLIST = 'REMOVE_MOVIE_FROM_WATCHLIST';
export const GET_SEARCHED_MOVIE = 'GET_SEARCHED_MOVIE';
