// Auth
export const AUTH_USER_SIGNED_IN = 'AUTH_USER_SIGNED_IN';
export const AUTH_USER_SIGNED_OUT = 'AUTH_USER_SIGNED_OUT';
export const AUTH_USER_SIGNED_UP = 'AUTH_USER_SIGNED_UP';
export const SET_AUTH_CURRENT_USER = 'SET_AUTH_CURRENT_USER';

// Movies
export const GET_ALL_MOVIES = 'GET_ALL_MOVIES';
export const GET_MOVIE_DETAIL = 'GET_MOVIE_DETAIL';
export const DELETE_SELECTED_MOVIE_DETAIL = 'DELETE_SELECTED_MOVIE_DETAIL';
export const ADD_MOVIE_TO_WATCHLIST = 'ADD_MOVIE_TO_WATCHLIST';
export const REMOVE_MOVIE_FROM_WATCHLIST = 'REMOVE_MOVIE_FROM_WATCHLIST';
export const GET_SEARCHED_MOVIE = 'GET_SEARCHED_MOVIE';
export const REMOVE_SEARCHED_MOVIES = 'REMOVE_SEARCHED_MOVIES';

// Components
export const SHOW_MESSAGE_COMPONENT = 'SHOW_MESSAGE_COMPONENT';
export const DESTROY_MESSAGE_COMPONENT = 'DESTROY_MESSAGE_COMPONENT';
